In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Data.csv')
df.sample(3)

   Country   Age   Salary Purchased
9   France  37.0  67000.0       Yes
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No

In [3]:
x = df.iloc[:, :-1]
y = df.iloc[:, -1:]

In [5]:
# Check missing rows 
df[df.isnull().any(axis = 1)]

   Country   Age   Salary Purchased
4  Germany  40.0      NaN       Yes
6    Spain   NaN  52000.0        No

In [8]:
# Get numerical columns only 
num_col = df.select_dtypes(include='number').columns
num_col

Index(['Age', 'Salary'], dtype='object')